START TRANSACTION;

DROP TABLE IF EXISTS customer_purchases;
DROP TABLE IF EXISTS art;
DROP TABLE IF EXISTS artists;
DROP TABLE IF EXISTS customers;

CREATE TABLE customers (
    customer_id serial,
    name varchar NOT NULL,
    address varchar NOT NULL,
    phone varchar,
    CONSTRAINT pk_customers PRIMARY KEY (customer_id)
);

CREATE TABLE artists (
    artist_id int GENERATED BY DEFAULT AS IDENTITY,
    first_name varchar(45) NOT NULL,
    last_name varchar(45) NOT NULL,
    CONSTRAINT pk_artists PRIMARY KEY (artist_id)
);

CREATE TABLE art (
    art_code varchar,
    title varchar NOT NULL,
    artist_id int NOT NULL,
    CONSTRAINT pk_art PRIMARY KEY (art_code),
    CONSTRAINT fk_art_artists FOREIGN KEY (artist_id) REFERENCES artists (artist_id)
);

CREATE TABLE customer_purchases (
    customer_id int NOT NULL,
    art_code varchar NOT NULL,
    purchase_date date NOT NULL,
    price numeric(2) NOT NULL,
    CONSTRAINT pk_customer_purchases PRIMARY KEY (customer_id, art_code, purchase_date),
    CONSTRAINT fk_cusotmer_purchases_customers 
        FOREIGN KEY (customer_id) REFERENCES customers (customer_id),
    CONSTRAINT fk_customer_purchases_art
        FOREIGN KEY (art_code) REFERENCES art (art_code)
);

COMMIT;